# Common settings
FROM node:22-bullseye AS base

# Copy source code
COPY . /app

# Set the working directory
WORKDIR /app

# --------for development--------
FROM base AS dev

# Install dependencies including devDependencies
RUN yarn install

# Start the development server
CMD ["yarn", "dev"]

# --------for production--------
FROM base AS prod

# Install dependencies excluding devDependencies
RUN yarn install --production

# Start the production server
CMD ["yarn", "start"]