# Common settings
FROM node:22-bullseye AS base

# Copy source code
COPY . /app

# Set the working directory
WORKDIR /app

# --------for development--------
FROM base AS dev

# Install dependencies including devDependencies
RUN npm ci

# --------for production--------
FROM base AS prod

# Install dependencies excluding devDependencies
RUN npm ci --only=production
