version: '3'

networks:
  app:

services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    networks:
      - app