version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env