FROM python:3.13-bullseye AS base

# Update pip and install pipenv
RUN pip3 install --upgrade pip
RUN pip3 install pipenv

COPY . /app
WORKDIR /app

# -------for development-------
FROM base AS dev

# Install dependencies
RUN pipenv install --dev

# Run server
CMD ["pipenv", "run", "start"]

# -------for production-------
FROM base AS prod

# Install dependencies
RUN pipenv install --deploy --system

# Run server
CMD ["pipenv", "run", "start"]