FROM amazonlinux:2023

# Install common tools
RUN yum install -y tar gzip zip unzip git curl wget vim

# Install Python 3 and pip
RUN yum install -y python3 python3-pip
RUN pip3 install --upgrade pip

# Copy source code
COPY . /app

# Install dependencies
RUN pip3 install -r /app/requirements.txt

# Set the working directory
WORKDIR /app